# Generated by Django 4.1.2 on 2022-10-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('PSTU_ID', models.CharField(max_length=50)),
                ('session', models.CharField(max_length=50)),
                ('fingerprint', models.CharField(max_length=10)),
                ('balance', models.IntegerField()),
            ],
        ),
    ]
