# Generated by Django 4.1.3 on 2023-02-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_machine"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="machineId",
            field=models.IntegerField(default=0),
        ),
    ]
